language: c

os: linux
dist: trusty

arch:
  - amd64
  - arm64
  - ppc64le

matrix:
  - compiler: gcc
  - compiler: clang
    env: CI_BUILD_PREFIX=scan-build

addons:
  apt:
    packages:
    - autogen
    - clang
    - libpcap-dev


script:
  - autoreconf -iv > build.log 2>&1 || (cat build.log && exit 1)
  - ${CI_BUILD_PREFIX} ./configure --enable-local-libopts > build.log 2>&1 || (cat build.log && exit 1)
  - ${CI_BUILD_PREFIX} make > build.log 2>&1 || (cat build.log && exit 1)
  - make dist > build.log 2>&1 || (cat build.log && exit 1)
  - make test || (cat test/test.log && exit 1)
